version: '3.8'
services:
  ansible-controller:
    build: .
    container_name: ansible-controller
    hostname: ansible-controller
    networks:
      ansible-net:
    volumes:
      - /home/admin1/Documents/Cty/learn_ansible:/etc/ansible/playbooks
    command: /bin/bash
    tty: true
  node1:
    build: .
    container_name: node1
    hostname: node1
    networks:
      ansible-net:
    volumes:
      - /home/admin1/Documents/Cty/learn_ansible/logs:/var/logs
    command: /bin/bash
    tty: true

  node2:
    build: .
    container_name: node2
    hostname: node2
    networks:
      ansible-net:
    volumes:
      - /home/admin1/Documents/Cty/learn_ansible/logs:/var/logs
    command: /bin/bash
    tty: true
networks:
  ansible-net:
    driver: bridge